# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionLabel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NutritionLabel',
            new_name='nutritionLabelModel',
        ),
    ]
